"""subs

Revision ID: b01e5e8be3f9
Revises: d061aeb736e7
Create Date: 2025-09-09 00:36:06.854594

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b01e5e8be3f9"
down_revision: Union[str, Sequence[str], None] = "d061aeb736e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("activated", sa.Boolean(), nullable=True),
        sa.Column("removed", sa.Boolean(), nullable=True),
        sa.Column("remark", sa.String(length=256), nullable=False),
        sa.Column("server_key", sa.String(length=64), nullable=False),
        sa.Column("access_key", sa.String(length=16), nullable=False),
        sa.Column("owner", sa.BigInteger(), nullable=True),
        sa.Column("expire", sa.BigInteger(), nullable=False),
        sa.Column("limit_usage", sa.BigInteger(), nullable=False),
        sa.Column("offset_usage", sa.BigInteger(), nullable=False),
        sa.Column("last_sub_updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_subscriptions_access_key"), "subscriptions", ["access_key"], unique=False)
    op.create_index(op.f("ix_subscriptions_id"), "subscriptions", ["id"], unique=False)
    op.create_index(op.f("ix_subscriptions_owner"), "subscriptions", ["owner"], unique=False)
    op.create_index(op.f("ix_subscriptions_remark"), "subscriptions", ["remark"], unique=False)
    op.create_index(op.f("ix_subscriptions_server_key"), "subscriptions", ["server_key"], unique=False)
    op.create_table(
        "subscription_usages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sub_id", sa.Integer(), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.Column("inbound_id", sa.Integer(), nullable=True),
        sa.Column("client_id", sa.Integer(), nullable=True),
        sa.Column("usage", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["servers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sub_id"],
            ["subscriptions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_subscription_usages_client_id"), "subscription_usages", ["client_id"], unique=False)
    op.create_index(op.f("ix_subscription_usages_inbound_id"), "subscription_usages", ["inbound_id"], unique=False)
    op.create_index(op.f("ix_subscription_usages_server_id"), "subscription_usages", ["server_id"], unique=False)
    op.create_index(op.f("ix_subscription_usages_sub_id"), "subscription_usages", ["sub_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_subscription_usages_sub_id"), table_name="subscription_usages")
    op.drop_index(op.f("ix_subscription_usages_server_id"), table_name="subscription_usages")
    op.drop_index(op.f("ix_subscription_usages_inbound_id"), table_name="subscription_usages")
    op.drop_index(op.f("ix_subscription_usages_client_id"), table_name="subscription_usages")
    op.drop_table("subscription_usages")
    op.drop_index(op.f("ix_subscriptions_server_key"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_remark"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_owner"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_id"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_access_key"), table_name="subscriptions")
    op.drop_table("subscriptions")
    # ### end Alembic commands ###
