"""improve settings

Revision ID: 32760534c6e1
Revises: b01e5e8be3f9
Create Date: 2025-09-10 18:16:10.498808

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "32760534c6e1"
down_revision: Union[str, Sequence[str], None] = "b01e5e8be3f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("setting", sa.Column("shuffle", sa.Boolean(), nullable=True))
    op.add_column("setting", sa.Column("placeholders", sa.JSON(), nullable=True))
    op.add_column("setting", sa.Column("informations", sa.JSON(), nullable=True))
    op.execute("UPDATE setting SET shuffle = FALSE, placeholders = '[]', informations = '[]'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("setting", "informations")
    op.drop_column("setting", "placeholders")
    op.drop_column("setting", "shuffle")
    # ### end Alembic commands ###
