"""servers

Revision ID: d061aeb736e7
Revises: ade6524c1846
Create Date: 2025-09-08 14:38:38.291802

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d061aeb736e7"
down_revision: Union[str, Sequence[str], None] = "ade6524c1846"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "servers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("remark", sa.String(length=128), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("removed", sa.Boolean(), nullable=True),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_servers_id"), "servers", ["id"], unique=False)
    op.create_table(
        "servers_access",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("access", sa.JSON(), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["servers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("servers_access")
    op.drop_index(op.f("ix_servers_id"), table_name="servers")
    op.drop_table("servers")
    # ### end Alembic commands ###
