from .env import (
    DEBUG,
    SQLALCHEMY_DATABASE_URL,
    TELEGRAM_ADMINS_ID,
    TELEGRAM_API_TOKEN,
    TELEGRAM_LOGGER_GROUP_ID,
    SUBSCRIPTION_DOMAIN_PREFIX,
)
from .tg import BOT, DP

__all__ = [
    "DEBUG",
    "SQLALCHEMY_DATABASE_URL",
    "TELEGRAM_ADMINS_ID",
    "TELEGRAM_API_TOKEN",
    "TELEGRAM_LOGGER_GROUP_ID",
    "BOT",
    "DP",
    "SUBSCRIPTION_DOMAIN_PREFIX",
]
